name: Binary Balance
description: Life on the digital knife edge
url: https://blog.binarybalance.com.au
author:
  name: Gaelian Ditchburn

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      path: ""
      type: posts
    values:
      is_post: true
sass:
  sass_dir: _scss
  style: compressed
markdown: kramdown
permalink: /:year/:month/:day/:title
exclude: ["gaelian.github.io.sublime-project", "Gemfile", "Gemfile.lock", "README.md"]
excerpt_separator: <!--more-->
feed:
  path: posts.atom
gems:
  - jekyll-redirect-from
  - jekyll-feed
